# Generated by Django 5.2.15 on 2026-06-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, unique=True)),
                ('name_bn', models.CharField(help_text='Bangla name (বাংলা নাম)', max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('companion', 'Companion Pet'), ('livestock', 'Livestock')], max_length=10)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier (e.g., lucide icon name or emoji)', max_length=50)),
                ('supports_rehoming', models.BooleanField(default=False, help_text='Can be listed for rehoming (cat and dog only)')),
                ('supports_services', models.BooleanField(default=False, help_text='Can be linked to service providers (companion pets only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Animal Type',
                'verbose_name_plural': 'Animal Types',
                'ordering': ['category', 'name_en'],
            },
        ),
    ]
