# Generated by Django 5.2.14 on 2026-05-31 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, unique=True)),
                ('name_bn', models.CharField(help_text='Bangla name (বাংলা নাম)', max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('companion', 'Companion Pet'), ('livestock', 'Livestock')], max_length=10)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier (e.g., lucide icon name or emoji)', max_length=50)),
                ('supports_rehoming', models.BooleanField(default=False, help_text='Can be listed for rehoming (cat and dog only)')),
                ('supports_services', models.BooleanField(default=False, help_text='Can be linked to service providers (companion pets only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Animal Type',
                'verbose_name_plural': 'Animal Types',
                'ordering': ['category', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name_en', models.CharField(max_length=100)),
                ('vaccine_name_bn', models.CharField(max_length=100)),
                ('disease_en', models.CharField(help_text='Disease(s) prevented', max_length=200)),
                ('disease_bn', models.CharField(max_length=200)),
                ('schedule_en', models.TextField(help_text='When to administer (e.g., "8 weeks, 12 weeks, annually")')),
                ('schedule_bn', models.TextField()),
                ('dosage', models.CharField(blank=True, help_text='Dosage info', max_length=100)),
                ('age_range', models.CharField(blank=True, help_text='Applicable age range (e.g., "6 weeks - 1 year")', max_length=50)),
                ('local_medicine_name', models.CharField(blank=True, help_text='Locally available medicine/brand names in Bangladesh', max_length=200)),
                ('notes_en', models.TextField(blank=True)),
                ('notes_bn', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='animals.animaltype')),
            ],
            options={
                'verbose_name': 'Vaccination Record',
                'verbose_name_plural': 'Vaccination Records',
                'ordering': ['animal_type', 'vaccine_name_en'],
            },
        ),
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_bn', models.CharField(max_length=200)),
                ('content_en', models.TextField()),
                ('content_bn', models.TextField()),
                ('summary_en', models.CharField(blank=True, max_length=300)),
                ('summary_bn', models.CharField(blank=True, max_length=300)),
                ('topic', models.CharField(choices=[('feeding', 'Feeding / খাওয়ানো'), ('health', 'Health / স্বাস্থ্য'), ('grooming', 'Grooming / পরিচর্যা'), ('training', 'Training / প্রশিক্ষণ'), ('housing', 'Housing / আবাসন'), ('breeding', 'Breeding / প্রজনন'), ('general', 'General Care / সাধারণ যত্ন')], default='general', max_length=20)),
                ('season', models.CharField(choices=[('all', 'All Seasons'), ('summer', 'Summer / গ্রীষ্ম'), ('monsoon', 'Monsoon / বর্ষা'), ('winter', 'Winter / শীত')], default='all', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to='animals.animaltype')),
            ],
            options={
                'verbose_name': 'Guideline',
                'verbose_name_plural': 'Guidelines',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['animal_type', 'topic'], name='animals_gui_animal__961711_idx'), models.Index(fields=['animal_type', 'season'], name='animals_gui_animal__c51ce5_idx')],
            },
        ),
    ]
