[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/v1/*"
  to = "https://petcareplus-django-backned.onrender.com/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
