version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: petcare_db
      POSTGRES_USER: petcare_user
      POSTGRES_PASSWORD: petcare_password
    ports:
      - "5432:5432"
    volumes:
      - petcare_postgres_data:/var/lib/postgresql/data

volumes:
  petcare_postgres_data:
