# Generated by Django 5.2.15 on 2026-06-22 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking', 'Booking'), ('application', 'Rehoming Application'), ('review', 'Review'), ('system', 'System')], default='system', max_length=15)),
                ('title_en', models.CharField(max_length=200)),
                ('title_bn', models.CharField(blank=True, max_length=200)),
                ('message_en', models.TextField(blank=True)),
                ('message_bn', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Frontend route to navigate to (e.g., /bookings/123)', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
