# Generated by Django 5.2.14 on 2026-05-31 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_history', models.JSONField(default=list, help_text='Array of {role: "user"|"assistant", content: "..."} objects')),
                ('total_turns', models.IntegerField(default=0)),
                ('urgency_level', models.CharField(blank=True, choices=[('monitor_at_home', 'Monitor at home / বাড়িতে পর্যবেক্ষণ করুন'), ('see_vet_this_week', 'See a vet this week / এই সপ্তাহে পশু চিকিৎসক দেখান'), ('call_vet_now', 'Call a vet now / এখনই পশু চিকিৎসক ডাকুন'), ('emergency', 'Emergency / জরুরি অবস্থা')], max_length=20)),
                ('ai_diagnosis_summary', models.TextField(blank=True, help_text='AI-generated diagnosis summary')),
                ('ai_care_advice', models.TextField(blank=True, help_text='AI-generated home care advice')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('animal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='animals.animaltype')),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Session',
                'verbose_name_plural': 'AI Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='1 = best match')),
                ('score', models.DecimalField(decimal_places=3, default=0, help_text='Weighted score used for ranking', max_digits=5)),
                ('reason_en', models.TextField(blank=True)),
                ('reason_bn', models.TextField(blank=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='providers.serviceprovider')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_suggestions', to='ai_assistant.aisession')),
            ],
            options={
                'verbose_name': 'AI Provider Suggestion',
                'verbose_name_plural': 'AI Provider Suggestions',
                'ordering': ['session', 'rank'],
                'unique_together': {('session', 'provider')},
            },
        ),
    ]
