# Generated by Django 5.2.9 on 2026-01-31 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicereview_provider_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_date', models.DateField(blank=True, help_text='Specific date to block (for one-time blocks)', null=True)),
                ('start_time', models.TimeField(blank=True, help_text='Start time of block', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time of block', null=True)),
                ('is_all_day', models.BooleanField(default=False, help_text='Block entire day')),
                ('is_recurring', models.BooleanField(default=False, help_text='Is this a recurring block?')),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], help_text='How often this block repeats', max_length=20, null=True)),
                ('day_of_week', models.IntegerField(blank=True, help_text='Day of week (0=Monday, 6=Sunday) for recurring blocks', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for blocking this time (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='services.serviceprovider')),
            ],
            options={
                'verbose_name': 'Availability Block',
                'verbose_name_plural': 'Availability Blocks',
                'ordering': ['-block_date', 'start_time'],
            },
        ),
    ]
