# Generated by Django 5.2.9 on 2026-01-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_provideravailabilityblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Provider preferences (notifications, auto-reply, etc.)'),
        ),
    ]
