# Generated by Django 5.2.9 on 2026-02-01 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_serviceprovider_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereview',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='services.servicebooking'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
