# Generated by Django 5.2.9 on 2026-02-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_servicereview_booking_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicereview',
            unique_together=set(),
        ),
    ]
