# Generated by Django 5.2.9 on 2026-02-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_servicereview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('cash', 'Cash'), ('platform', 'Platform Payment')], default='platform', max_length=20),
        ),
    ]
