# Generated by Django 5.2.9 on 2026-02-04 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
        ('services', '0012_servicebooking_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='guest_client_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='guest_pet_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='pets.petprofile'),
        ),
    ]
