# Generated by Django 5.2.9 on 2026-02-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_number_alter_user_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_country',
            field=models.CharField(max_length=100),
        ),
    ]
