# Generated by Django 5.2.15 on 2026-06-22 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('description_en', models.TextField(blank=True)),
                ('description_bn', models.TextField(blank=True)),
                ('provider_type', models.CharField(choices=[('vet', 'Veterinarian / পশু চিকিৎসক'), ('groomer', 'Groomer / গ্রুমার'), ('sitter', 'Pet Sitter / পেট সিটার'), ('trainer', 'Trainer / প্রশিক্ষক'), ('pharmacy', 'Pharmacy / ফার্মেসি')], default='vet', max_length=10)),
                ('is_government_vet', models.BooleanField(default=False, help_text='Indicates if this is a Government Vet')),
                ('profile_image_url', models.URLField(blank=True, help_text='Direct link to profile image', max_length=500, null=True)),
                ('division', models.CharField(choices=[('barishal', 'বরিশাল (Barishal)'), ('chattogram', 'চট্টগ্রাম (Chattogram)'), ('dhaka', 'ঢাকা (Dhaka)'), ('khulna', 'খুলনা (Khulna)'), ('mymensingh', 'ময়মনসিংহ (Mymensingh)'), ('rajshahi', 'রাজশাহী (Rajshahi)'), ('rangpur', 'রংপুর (Rangpur)'), ('sylhet', 'সিলেট (Sylhet)')], max_length=20)),
                ('district', models.CharField(max_length=50)),
                ('upazila', models.CharField(blank=True, max_length=50)),
                ('union', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin')),
                ('is_active', models.BooleanField(default=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated average rating', max_digits=3)),
                ('total_reviews', models.IntegerField(default=0, help_text='Auto-calculated total review count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'ordering': ['-avg_rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_bn', models.CharField(blank=True, max_length=100)),
                ('description_en', models.TextField(blank=True)),
                ('description_bn', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in BDT', max_digits=10, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Approximate duration in minutes', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.serviceprovider')),
            ],
            options={
                'verbose_name': 'Provider Service',
                'verbose_name_plural': 'Provider Services',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='ProviderAnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_links', to='animals.animaltype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_types', to='providers.serviceprovider')),
            ],
            options={
                'verbose_name': 'Provider Animal Type',
                'verbose_name_plural': 'Provider Animal Types',
            },
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['provider_type', 'is_verified'], name='providers_s_provide_fc03e6_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['division', 'district'], name='providers_s_divisio_7cf496_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['avg_rating'], name='providers_s_avg_rat_950762_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='provideranimaltype',
            unique_together={('provider', 'animal_type')},
        ),
    ]
