# Generated by Django 5.2.15 on 2026-06-23 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='serviceprovider',
            name='providers_s_divisio_7cf496_idx',
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['division', 'district', 'upazila'], name='providers_s_divisio_05d3f2_idx'),
        ),
    ]
