# Generated by Django 5.2.14 on 2026-06-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_serviceprovider_latitude_serviceprovider_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='is_government_vet',
            field=models.BooleanField(default=False, help_text='Indicates if this is a Government Vet'),
        ),
    ]
