# Generated by Django 5.2.15 on 2026-06-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('providers', '0002_remove_serviceprovider_providers_s_divisio_7cf496_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serviceprovider',
            new_name='providers_s_divisio_cac7df_idx',
            old_name='providers_s_divisio_05d3f2_idx',
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='locations.district'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='locations.division'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='locations.union'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='locations.upazila'),
        ),
    ]
