# Generated by Django 5.2.14 on 2026-06-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_serviceprovider_is_government_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Direct link to profile image', max_length=500, null=True),
        ),
    ]
