# Generated by Django 5.2.15 on 2026-06-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_favoriteprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='union',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
