# Generated by Django 5.2.15 on 2026-06-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_serviceprovider_union'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteProvider',
        ),
    ]
