# Generated by Django 5.2.15 on 2026-06-22 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('division', models.CharField(blank=True, choices=[('barishal', 'বরিশাল (Barishal)'), ('chattogram', 'চট্টগ্রাম (Chattogram)'), ('dhaka', 'ঢাকা (Dhaka)'), ('khulna', 'খুলনা (Khulna)'), ('mymensingh', 'ময়মনসিংহ (Mymensingh)'), ('rajshahi', 'রাজশাহী (Rajshahi)'), ('rangpur', 'রংপুর (Rangpur)'), ('sylhet', 'সিলেট (Sylhet)')], help_text='বিভাগ (Division)', max_length=20)),
                ('district', models.CharField(blank=True, help_text='জেলা (District)', max_length=50)),
                ('upazila', models.CharField(blank=True, help_text='উপজেলা (Upazila)', max_length=50)),
                ('union', models.CharField(blank=True, help_text='ইউনিয়ন (Union)', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='অক্ষাংশ (Latitude)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='দ্রাঘিমাংশ (Longitude)', max_digits=9, null=True)),
                ('preferred_language', models.CharField(choices=[('bn', 'বাংলা (Bangla)'), ('en', 'English')], default='bn', help_text='Preferred language for content and UI', max_length=2)),
                ('role', models.CharField(choices=[('pet_owner', 'Pet Owner'), ('farmer', 'Farmer'), ('provider', 'Service Provider'), ('admin', 'Admin')], default='pet_owner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Item',
                'verbose_name_plural': 'Saved Items',
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
