# Generated by Django 5.2.14 on 2026-06-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='অক্ষাংশ (Latitude)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='দ্রাঘিমাংশ (Longitude)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='union',
            field=models.CharField(blank=True, help_text='ইউনিয়ন (Union)', max_length=50),
        ),
    ]
