# Generated by Django 5.2.15 on 2026-06-22 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RehomingListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('age', models.DecimalField(blank=True, decimal_places=1, help_text='Age in years', max_digits=4, null=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spayed_neutered', models.BooleanField(default=False)),
                ('vaccinated', models.BooleanField(default=False)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('district', models.CharField(blank=True, help_text='জেলা (District) of the pet/owner', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for distance matching', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for distance matching', max_digits=9, null=True)),
                ('reason', models.TextField(help_text='Reason for rehoming')),
                ('adopter_requirements', models.TextField(blank=True, help_text='Requirements for the potential adopter (e.g. Must have yard, no other pets)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('adopted', 'Adopted'), ('withdrawn', 'Withdrawn')], default='active', max_length=10)),
                ('policy_accepted', models.BooleanField(default=False, help_text='User agreed to safety and responsibility guidelines')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_type', models.ForeignKey(help_text='Must be a companion animal (cat, dog)', on_delete=django.db.models.deletion.PROTECT, related_name='rehoming_listings', to='animals.animaltype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehoming_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rehoming Listing',
                'verbose_name_plural': 'Rehoming Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RehomingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Why do you want to adopt this pet?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('ai_score', models.IntegerField(blank=True, help_text='AI-generated matching score out of 10', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehoming_applications', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='rehoming.rehominglisting')),
            ],
            options={
                'verbose_name': 'Rehoming Application',
                'verbose_name_plural': 'Rehoming Applications',
                'ordering': ['-created_at'],
                'unique_together': {('listing', 'applicant')},
            },
        ),
    ]
