# Generated by Django 6.0.6 on 2026-06-18 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RehomingListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spayed_neutered', models.BooleanField(default=False)),
                ('vaccinated', models.BooleanField(default=False)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('reason', models.TextField(help_text='Reason for rehoming')),
                ('status', models.CharField(choices=[('active', 'Active'), ('adopted', 'Adopted'), ('withdrawn', 'Withdrawn')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_type', models.ForeignKey(help_text='Must be a companion animal (cat, dog)', on_delete=django.db.models.deletion.PROTECT, related_name='rehoming_listings', to='animals.animaltype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehoming_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rehoming Listing',
                'verbose_name_plural': 'Rehoming Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RehomingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Why do you want to adopt this pet?')),
                ('living_situation', models.TextField(blank=True, help_text='Describe your living situation')),
                ('experience', models.TextField(blank=True, help_text='Previous pet ownership experience')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehoming_applications', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='rehoming.rehominglisting')),
            ],
            options={
                'verbose_name': 'Rehoming Application',
                'verbose_name_plural': 'Rehoming Applications',
                'ordering': ['-created_at'],
                'unique_together': {('listing', 'applicant')},
            },
        ),
    ]
