# Generated by Django 5.2.14 on 2026-05-31 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RehomingListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for rehoming')),
                ('status', models.CharField(choices=[('active', 'Active'), ('adopted', 'Adopted'), ('withdrawn', 'Withdrawn')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehoming_listings', to=settings.AUTH_USER_MODEL)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rehoming_listing', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Rehoming Listing',
                'verbose_name_plural': 'Rehoming Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RehomingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Why do you want to adopt this pet?')),
                ('living_situation', models.TextField(blank=True, help_text='Describe your living situation')),
                ('experience', models.TextField(blank=True, help_text='Previous pet ownership experience')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehoming_applications', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='rehoming.rehominglisting')),
            ],
            options={
                'verbose_name': 'Rehoming Application',
                'verbose_name_plural': 'Rehoming Applications',
                'ordering': ['-created_at'],
                'unique_together': {('listing', 'applicant')},
            },
        ),
    ]
