# Generated by Django 6.0.6 on 2026-06-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehoming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehominglisting',
            name='adopter_requirements',
            field=models.TextField(blank=True, help_text='Requirements for the potential adopter (e.g. Must have yard, no other pets)'),
        ),
        migrations.AddField(
            model_name='rehominglisting',
            name='district',
            field=models.CharField(blank=True, help_text='জেলা (District) of the pet/owner', max_length=50),
        ),
        migrations.AddField(
            model_name='rehominglisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for distance matching', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rehominglisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for distance matching', max_digits=9, null=True),
        ),
    ]
