# Generated by Django 6.0.6 on 2026-06-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehoming', '0002_rehominglisting_adopter_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehomingapplication',
            name='ai_score',
            field=models.IntegerField(blank=True, help_text='AI-generated matching score out of 10', null=True),
        ),
    ]
