# Generated by Django 6.0.6 on 2026-06-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehoming', '0003_rehomingapplication_ai_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehomingapplication',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='rehomingapplication',
            name='living_situation',
        ),
        migrations.RemoveField(
            model_name='rehominglisting',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='rehominglisting',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Age in years', max_digits=4, null=True),
        ),
    ]
