# Generated by Django 6.0.6 on 2026-06-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehoming', '0004_remove_rehomingapplication_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehominglisting',
            name='policy_accepted',
            field=models.BooleanField(default=False, help_text='User agreed to safety and responsibility guidelines'),
        ),
    ]
