# Generated by Django 5.2.15 on 2026-06-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehoming', '0005_rehominglisting_policy_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehomingapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
