# Generated by Django 5.2.15 on 2026-06-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_bn', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('govt', 'Government Office'), ('emergency', 'Emergency Contact'), ('vaccination', 'Vaccination'), ('medicine', 'Medicine'), ('diseases', 'Diseases'), ('information', 'Information'), ('shelter', 'Shelter'), ('food', 'Food'), ('other', 'Other')], default='information', max_length=20)),
                ('description_en', models.TextField(blank=True)),
                ('description_bn', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_types', models.ManyToManyField(blank=True, related_name='resources', to='animals.animaltype')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type'], name='resources_r_resourc_1a6f3f_idx'), models.Index(fields=['is_active'], name='resources_r_is_acti_cf90e4_idx'), models.Index(fields=['title_en'], name='resources_r_title_e_41164a_idx'), models.Index(fields=['title_bn'], name='resources_r_title_b_90f076_idx')],
            },
        ),
    ]
