# Generated by Django 5.2.14 on 2026-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovtResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_bn', models.CharField(max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_bn', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('govt', 'Government Office'), ('ngo', 'NGO'), ('emergency', 'Emergency Contact')], default='govt', max_length=10)),
                ('division', models.CharField(choices=[('barishal', 'বরিশাল (Barishal)'), ('chattogram', 'চট্টগ্রাম (Chattogram)'), ('dhaka', 'ঢাকা (Dhaka)'), ('khulna', 'খুলনা (Khulna)'), ('mymensingh', 'ময়মনসিংহ (Mymensingh)'), ('rajshahi', 'রাজশাহী (Rajshahi)'), ('rangpur', 'রংপুর (Rangpur)'), ('sylhet', 'সিলেট (Sylhet)')], max_length=20)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_en', models.TextField(blank=True)),
                ('address_bn', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Government Resource',
                'verbose_name_plural': 'Government Resources',
                'ordering': ['division', 'resource_type', 'name_en'],
                'indexes': [models.Index(fields=['division', 'district'], name='resources_g_divisio_7807cd_idx'), models.Index(fields=['resource_type'], name='resources_g_resourc_394778_idx')],
            },
        ),
    ]
