# Generated by Django 5.2.15 on 2026-06-20 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_bn', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('govt', 'Government Office'), ('emergency', 'Emergency Contact'), ('vaccination', 'Vaccination'), ('medicine', 'Medicine'), ('diseases', 'Diseases'), ('information', 'Information'), ('other', 'Other')], default='information', max_length=20)),
                ('description_en', models.TextField(blank=True)),
                ('description_bn', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='animals.animaltype')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GovtResource',
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type'], name='resources_r_resourc_1a6f3f_idx'),
        ),
    ]
