# Generated by Django 5.2.15 on 2026-06-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_delete_govtresource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('govt', 'Government Office'), ('emergency', 'Emergency Contact'), ('vaccination', 'Vaccination'), ('medicine', 'Medicine'), ('diseases', 'Diseases'), ('information', 'Information'), ('shelter', 'Shelter'), ('food', 'Food'), ('other', 'Other')], default='information', max_length=20),
        ),
    ]
