# Generated by Django 5.2.15 on 2026-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('resources', '0003_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['animal_type'], name='resources_r_animal__5b54ec_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_active'], name='resources_r_is_acti_cf90e4_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['title_en'], name='resources_r_title_e_41164a_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['title_bn'], name='resources_r_title_b_90f076_idx'),
        ),
    ]
