# Generated by Django 5.2.15 on 2026-06-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('resources', '0004_resource_resources_r_animal__5b54ec_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resource',
            name='resources_r_animal__5b54ec_idx',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='animal_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='animal_types',
            field=models.ManyToManyField(blank=True, related_name='resources', to='animals.animaltype'),
        ),
    ]
